
[General]
	#The number of item stacks held in a basic unit of storage.
	#1x1 drawers hold 8 units, 1x2 drawers hold 4 units, 2x2 drawers hold 2 units.
	#Half-depth drawers hold half those amounts.
	baseStackStorage = 4
	#Controller range defines how far away a drawer can be connected
	#on X, Y, or Z planes.  The default value of 50 gives the controller a very
	#large range, but not beyond the chunk load distance.
	#Range: 1 ~ 75
	controllerRange = 50
	enableUI = true
	enableSidedInput = true
	enableSidedOutput = true
	enableItemConversion = true
	enableExtraCompactingRules = true
	debugTrace = false
	#List of rules in format "domain:item1, domain:item2, n".
	#Creates a compacting drawer rule to convert 1 of item1 into n of item2.
	compactingRules = ["beyond_earth:desh_block, beyond_earth:desh_ingot, 9", "beyond_earth:desh_ingot, beyond_earth:desh_nugget, 9", "beyond_earth:ostrum_block, beyond_earth:ostrum_ingot, 9", "beyond_earth:ostrum_ingot, beyond_earth:ostrum_nugget, 9", "beyond_earth:calorite_block, beyond_earth:calorite_ingot, 9", "beyond_earth:calorite_ingot, beyond_earth:calorite_nugget, 9", "refinedstorage:quartz_enriched_iron_block, refinedstorage:quartz_enriched_iron, 9", "powah:energized_steel_block, powah:energized_steel, 9", "minecraft:coal, opolisutilities:mini_coal, 8", "minecraft:charcoal, opolisutilities:mini_charcoal, 8", "minecraft:clay, minecraft:clay_ball, 4", "compressium:cobblestone_2, compressium:cobblestone_1, 9", "compressium:cobblestone_1, minecraft:cobblestone, 9", "compressium:stone_2, compressium:stone_1, 9", "compressium:stone_1, minecraft:stone, 9"]

[StorageUpgrades]
	#Storage upgrades multiply storage capacity by the given amount.
	#When multiple storage upgrades are used together, their multipliers are added before being applied.
	level1Mult = 2
	level2Mult = 4
	level3Mult = 8
	level4Mult = 16
	level5Mult = 32

[Integration]
	#When true, shows quantity as NxS + R (by stack size) rather than count
	wailaStackRemainder = true
	#When true, does not show current quantities unless quantify key was used
	wailaRespectQuantifyKey = false

